// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA-z2A-FaajDudE_4m-j4biMjIevLpp2Y',
    appId: '1:287644110558:web:3dd71ebe6e753594d7fc4f',
    messagingSenderId: '287644110558',
    projectId: 'habittracker-9f34a',
    authDomain: 'habittracker-9f34a.firebaseapp.com',
    storageBucket: 'habittracker-9f34a.firebasestorage.app',
    measurementId: 'G-NK05V6ECNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASZffKMRWJTrcq-kInIOLkLKo_JmW6tKw',
    appId: '1:287644110558:android:df00be3ebd6fdc26d7fc4f',
    messagingSenderId: '287644110558',
    projectId: 'habittracker-9f34a',
    storageBucket: 'habittracker-9f34a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY4emJ_OhvRdTW9uZ_Ad4ZAZ--i-FnHSw',
    appId: '1:287644110558:ios:aa350c4ecb7386b6d7fc4f',
    messagingSenderId: '287644110558',
    projectId: 'habittracker-9f34a',
    storageBucket: 'habittracker-9f34a.firebasestorage.app',
    androidClientId: '287644110558-bc2gps2cec6b3tnj26m0s741ckbe6icm.apps.googleusercontent.com',
    iosClientId: '287644110558-2i4clt8hk7kq22bs44phedbvs71soaga.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY4emJ_OhvRdTW9uZ_Ad4ZAZ--i-FnHSw',
    appId: '1:287644110558:ios:aa350c4ecb7386b6d7fc4f',
    messagingSenderId: '287644110558',
    projectId: 'habittracker-9f34a',
    storageBucket: 'habittracker-9f34a.firebasestorage.app',
    androidClientId: '287644110558-bc2gps2cec6b3tnj26m0s741ckbe6icm.apps.googleusercontent.com',
    iosClientId: '287644110558-2i4clt8hk7kq22bs44phedbvs71soaga.apps.googleusercontent.com',
    iosBundleId: 'com.example.habitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA-z2A-FaajDudE_4m-j4biMjIevLpp2Y',
    appId: '1:287644110558:web:ccc55aec66d6543fd7fc4f',
    messagingSenderId: '287644110558',
    projectId: 'habittracker-9f34a',
    authDomain: 'habittracker-9f34a.firebaseapp.com',
    storageBucket: 'habittracker-9f34a.firebasestorage.app',
    measurementId: 'G-6KT29MQ0FR',
  );
}
