name: habit_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  
  flutter:
    sdk: flutter
  flutter_heatmap_calendar: ^1.0.5
  get: ^4.7.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.5.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.5.4
  analyzer: ^6.11.0
  
